package br.edu.securitystore.iam.authorization.core.domain;

public enum PermissionCode {
    IDENTITY_USER_READ, IDENTITY_USER_CREATE, IDENTITY_USER_UPDATE, IDENTITY_USER_DISABLE, IDENTITY_USER_ENABLE,
    AUTHENTICATION_SESSION_READ, AUTHENTICATION_SESSION_REVOKE,
    AUTHORIZATION_ROLE_READ, AUTHORIZATION_ROLE_CREATE, AUTHORIZATION_ROLE_UPDATE, AUTHORIZATION_ROLE_DELETE,
    AUTHORIZATION_PERMISSION_READ, AUTHORIZATION_USER_ROLE_READ, AUTHORIZATION_USER_ROLE_ASSIGN, AUTHORIZATION_USER_ROLE_REVOKE,
    CATALOG_PRODUCT_WRITE, SALES_ORDER_READ_ALL, SALES_DELIVERY_UPDATE
}
